# Generated by Django 3.2.4 on 2021-06-21 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=1000)),
                ('url', models.URLField(unique=True)),
            ],
            options={
                'verbose_name': 'coach',
                'verbose_name_plural': 'coachs',
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.TextField(blank=True, default='')),
                ('evaluation', models.DecimalField(decimal_places=1, max_digits=2)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='coachs.coach')),
            ],
            options={
                'verbose_name': ('Avaliação',),
                'verbose_name_plural': 'Avaliações',
                'unique_together': {('email', 'coach')},
            },
        ),
    ]
