# Generated by Django 3.2.4 on 2021-06-22 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coachs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.TextField(blank=True, default='')),
                ('valuation', models.DecimalField(decimal_places=1, max_digits=2)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='coachs.coach')),
            ],
            options={
                'verbose_name': ('Avaliação',),
                'verbose_name_plural': 'Avaliações',
                'unique_together': {('email', 'coach')},
            },
        ),
        migrations.DeleteModel(
            name='Evaluation',
        ),
    ]
